name: task_intern
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  printing: ^5.13.3
  path_provider: ^2.1.4
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/resume1.png
    - images/resume2.png
    - images/resume3.png
    - images/resume4.png
    - images/main_resume.png
    - images/back.jpeg
    - images/back1.jpeg
    - images/back2.jpeg
